In [2]:

! pip install torch torchvision


In [12]:
import numpy as np
import torch

t = np.array([0, 1, 2, 3, 4, 5, 6])
print(t)

print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

print('t[0] t[1] t[-1] :', t[0], t[1], t[-1])
print('t[2:5] t[4:-1] :', t[2:5], t[4:-1])
print('t[:2] t[3:] :', t[:2], t[3:])

[0 1 2 3 4 5 6]
Rank of t :  1
Shape of t :  (7,)
t[0] t[1] t[-1] : 0 1 6
t[2:5] t[4:-1] : [2 3 4] [4 5]
t[:2] t[3:] : [0 1] [3 4 5 6]


In [15]:
t = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]
])
print(t)

print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Rank of t :  2
Shape of t :  (4, 3)


In [20]:
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [22]:
t = torch.FloatTensor([
              [1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]
])
print(t)

print('Rank of t : ', t.dim())
print('Shape of t : ', t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
Rank of t :  2
Shape of t :  torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [24]:
# boardcast
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1+m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [27]:
print()
print('-------------')
print('Mul VS Matmul')
print('-------------')

m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1 * m2)
print(m1.mul(m2))


-------------
Mul VS Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [30]:
# Mean
t = torch.FloatTensor([1,2])
print(t.mean())

t = torch.LongTensor([1,2])
try : 
  print(t.mean())
except Exception as exc:
  print(exc)

t = torch.FloatTensor([[1,2], [3,4]])
print(t)

print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim = -1))

tensor(1.5000)
Can only calculate the mean of floating types. Got Long instead.
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [33]:
# sum
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))
print(t.sum(dim = -2))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])
tensor([4., 6.])


In [37]:
# Max and Argmax
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

print(t.max())

print(t.max(dim=0)[0]) # max
print(t.max(dim=0)[1]) # arg max

print(t.max(dim=1)[0]) # max
print(t.max(dim=1)[1]) # arg max

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
tensor([3., 4.])
tensor([1, 1])
tensor([2., 4.])
tensor([1, 1])


In [41]:
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]])

ft = torch.FloatTensor(t)

print(ft.shape)

print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)



torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
